# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

substitutions:
  _TEST_VAR: v6.9.1 
    
# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - git@github.com:pratibajagnere/testGH
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/pjagnere-jarvis/secrets/secretGH/versions/latest
    env: 'SSH_KEY'
